"""Single A2A seller agent entrypoint. Generated by `bag recipe code agent`.

This is the VALUABLE agent AND the SOLE key-holder/signer. It serves its two
ERC-8183 seller skills DIRECTLY over the A2A protocol on AWS Bedrock AgentCore
(``--protocol A2A``): AgentCore's ``serve_a2a`` wraps the official ``a2a-sdk`` and
exposes the agent card at ``/.well-known/agent-card.json`` + JSON-RPC
``message/send`` on ``0.0.0.0:9000`` (``AGENT_PORT`` overrides locally). There
is no separate forwarding service — the
agent IS the seller (see executor.py + agent_card.py).

A2A skills (executor.py):

    negotiate     → read the FIXED list price → CLAMP to [min,max] → EIP-191 SIGN
                    the offer (no LLM, no tools) → return the signed offer (or reject)
    notify_funded → re-verify the funded job on-chain (fast) → ACK accepted at once,
                    then in the BACKGROUND: LLM work → manifest → storage →
                    submit_result (SIGN + broadcast). The buyer polls the chain for
                    the deliverable. Each notify also sweeps other FUNDED jobs
                    (buyer-push fallback). While background work is in flight the
                    ``ping_handler`` reports HEALTHY_BUSY so AgentCore keeps the
                    scale-to-zero runtime warm until it lands.

Buyers reach this endpoint with an OAuth2 (Cognito) bearer — AgentCore A2A
mandates inbound auth (see agent_card.py + ``bag deploy provision-cognito``).

## Boundaries (do NOT cross — they are the whole point)

- The agent does ALL deterministic SIGNING (quote-sign + submit + settle +
  automatic x402 LLM-credit auto-renew). ALL signing is FIXED code in
  ``signing.py`` — NEVER an LLM-callable tool (money never in the LLM).
- The price is a FIXED list price from studio.toml (clamped before signing) —
  the LLM never prices; it only PRODUCES the work text in ``fulfill``.
- Chain access for the LLM is READ-ONLY tools only (``tools.py``).
- ``settle`` (claim payment after the dispute window) is operator-driven — run
  ``bag erc8183 settle <job_id>``; it is deliberately NOT an A2A skill.
"""
from __future__ import annotations

import json
import logging
import os
import sys
import time

from google.adk.agents import Agent
from google.adk.runners import InMemoryRunner
from google.genai import types as gtypes

from managed_model import build_model
from bnbagent_studio_core.wallet import (
    ensure_keystore_materialized,
    ensure_twak_materialized,
)

from agent_card import build_agent_card
from executor import SellerAgentExecutor
from tools import LLM_READ_TOOLS

APP_NAME = "agent"


# --- Logging -------------------------------------------------------------------
# Make the agent's own logs visible in `docker logs` / CloudWatch — ESPECIALLY
# the BACKGROUND notify_funded delivery, which runs AFTER the A2A ack (off the
# request path). Without this the "seller-agent.*" loggers inherit the root
# config (which opentelemetry / AgentCore may leave at WARNING or route away),
# so a delivery that fails — e.g. a missing STORAGE_API_URL at the IPFS-pin step
# — vanishes silently while the buyer polls the chain forever. We attach our own
# stdout handler at INFO so success AND failure are always on stdout.
def _configure_logging() -> None:
    log = logging.getLogger("seller-agent")
    if log.handlers:  # idempotent (cold start may re-import)
        return
    handler = logging.StreamHandler(sys.stdout)
    handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)s %(name)s: %(message)s"))
    log.addHandler(handler)
    log.setLevel(logging.INFO)
    log.propagate = False  # don't double-log via the root handler


_configure_logging()


def _generator_tag() -> str:
    """Deliverable ``generator`` label: this seller's own name, read from
    studio.toml ``[project].name`` (minus the ``-agent`` suffix) so each
    delivered manifest is self-identifying. Best-effort — falls back to
    ``APP_NAME`` if the config can't be read."""
    try:
        from bnbagent_studio_core import config

        name = str(((config.load_studio_toml() or {}).get("project") or {}).get("name") or "")
    except Exception:  # noqa: BLE001 — a metadata label must never break fulfill
        return APP_NAME
    return name[: -len("-agent")] if name.endswith("-agent") else (name or APP_NAME)


GENERATOR = _generator_tag()


# --- Runtime secrets -----------------------------------------------------------
# Keep plaintext secrets OUT of agentcore.json. When BNBAGENT_RUNTIME_SECRET_ID is set
# (deployed runtime), pull a JSON {ENV_NAME: value} blob from AWS Secrets Manager
# into the process env BEFORE anything reads it (keystore unlock, provider key,
# build_model, Cognito OAuth env). No-op locally, where .env.local already
# populated the environment — `setdefault` never overrides an already-present var.
def _load_runtime_secrets() -> None:
    secret_id = os.environ.get("BNBAGENT_RUNTIME_SECRET_ID")
    if not secret_id:
        return
    import boto3

    resp = boto3.client("secretsmanager").get_secret_value(SecretId=secret_id)
    for key, value in json.loads(resp["SecretString"]).items():
        os.environ.setdefault(key, str(value))


_load_runtime_secrets()

# --- Wallet bootstrap -----------------------------------------------------------
# Wallet material is NEVER bundled into the deploy artifact. `bag deploy`
# injects it via Secrets Manager and these calls (run once at cold start,
# before any signing) materialize it on disk. Each is a no-op for the other
# wallet kind and locally, where the wallet already lives on disk:
#  - evm-local: WALLET_KEYSTORE_JSON → keystore file (unlocked with WALLET_PASSWORD)
#  - twak:      TWAK_WALLET_JSON / TWAK_CREDENTIALS_JSON → $TMPDIR/twak-home/.twak
#               (exported as TWAK_HOME_DIR; twak reads TWAK_WALLET_PASSWORD itself)
ensure_keystore_materialized()
ensure_twak_materialized()

# --- Agent + runtime ----------------------------------------------------------
# LLM credit auto-renew (Pieverse path): `build_model()` (in managed_model.py)
# returns a managed model wrapper that auto-tops up the active Pieverse key
# before each generate call when [llm.auto_renew] is enabled. That top-up is
# the ONLY automatic signing path outside signing.py — it is budget-gated and
# is NOT an LLM tool. It rides transparently into `fulfill`.
#
# trap: Agent.name must be a valid Python identifier — no hyphens. ADK silently
# misbehaves on names containing "-".
#
# The LLM runs ONLY in `fulfill` (the value hook). `negotiate` is rule-based and
# never touches the LLM. The read-only chain tools are attached so the work can
# read on-chain context if it needs to — drop them from `tools.py` if your work
# doesn't read chain. Signing / settle are NEVER tools — they are fixed code in
# signing.py, triggered by the A2A skills, never callable by the LLM. (The one
# deliberate exception: the x402-buyer recipe's PAID fetch tools — see the
# `tools=` note below — the LLM picks the URL, but who gets paid and the
# per-call/daily caps stay locked in studio.toml.)
_model = build_model()  # managed model with the auto-renew hook (fulfill only)

agent = Agent(
    name="seller_agent",
    model=_model,
    instruction=(
        "You are a seller agent whose specific job is: explain ERC-8004 identity and ERC-8183 job-escrow hiring to a total beginner, in plain simple English with real analogies and no jargon."
        "Be concrete and concise. Use the read-only chain tools when on-chain "
        "context helps. If a paid-data tool such as `buy_with_x402` is available "
        "to you, USE IT to fetch the data a task needs — those merchants (e.g. "
        "CoinMarketCap) charge via on-chain wallet payment, NOT an API key; never "
        "reply that you cannot complete the task for lack of an API key."
    ),
    # LLM_READ_TOOLS = read-only chain tools (wallet, balances, ERC-8004/8183
    # queries). Edit `tools.py` to add/remove. These are READ-ONLY — the agent
    # never signs via a tool; all signing is in signing.py (fixed code).
    # To let the agent BUY paid data at work time (e.g. CMC market data after
    # `bag x402 trust cmc` + `bag recipe code x402-buyer`), append the emitted
    # tool set — payee + per-call/daily caps stay locked in studio.toml:
    #   from x402_buyer import x402_buyer_set
    #   tools=[*LLM_READ_TOOLS, *x402_buyer_set],
    tools=LLM_READ_TOOLS,
)
runner = InMemoryRunner(agent=agent, app_name=APP_NAME)


# --- One-shot LLM helper (the executor's `fulfill` work hook) ------------------
async def _run_llm(prompt: str, *, session_id: str) -> str:
    """Run the agent once and return the concatenated final-response text.

    `fulfill` produces a single deliverable (not an SSE stream), so we collect
    the final response text. The session is created on the runner's own
    session_service (a separate InMemorySessionService would raise "Session not
    found" on run_async).
    """
    session_service = runner.session_service
    existing = await session_service.get_session(
        app_name=runner.app_name, user_id="service", session_id=session_id
    )
    if existing is None:
        await session_service.create_session(
            app_name=runner.app_name, user_id="service", session_id=session_id
        )

    user_msg = gtypes.Content(role="user", parts=[gtypes.Part(text=prompt)])
    parts: list[str] = []
    async for event in runner.run_async(
        user_id="service", session_id=session_id, new_message=user_msg
    ):
        if event.is_final_response() and event.content:
            for p in event.content.parts:
                if p.text:
                    parts.append(p.text)
    return "\n".join(parts).strip()


def _default_network() -> str:
    """studio.toml ``[network].default`` (best-effort; used by the funded sweep)."""
    try:
        from bnbagent_studio_core import config

        return str(((config.load_studio_toml() or {}).get("network") or {}).get("default") or "bsc-testnet")
    except Exception:  # noqa: BLE001
        return "bsc-testnet"


# --- A2A surface --------------------------------------------------------------
# The executor backs the seller skills with signing.py fixed code (NEVER an LLM
# tool). serve_a2a (AgentCore SDK, built on the official a2a-sdk) hosts the agent
# card + JSON-RPC message/send on 0.0.0.0:9000, adds GET /ping, and overwrites
# the card url with the deployed runtime URL ($AGENTCORE_RUNTIME_URL).
executor = SellerAgentExecutor(
    run_work=_run_llm, generator=GENERATOR, network=_default_network()
)
agent_card = build_agent_card()


async def _serve_deliverable(request):
    """GET /erc8183/job/{job_id}/response — real, third bug fixed 2026-08-19.

    Real Render log: job #56619's submit() genuinely reached this far (LLM
    succeeded, both earlier event-loop bugs fixed) and then failed with:
    "Cannot publish deliverable: storage returned a non-public URL and
    ERC8183_AGENT_URL is not set." studio.toml's [storage].kind = "local"
    (LocalStorageProvider) writes file:// URLs, which submit() refuses to
    publish on-chain without ERC8183_AGENT_URL configured — and per the
    SDK's own docstring (bnbagent.storage.StorageProvider.uses_file_url),
    the agent is expected to serve GET {ERC8183_AGENT_URL}/job/{id}/response
    itself; nothing in bag's scaffolded main.py/executor.py did that until
    now (confirmed by grepping the real generated source — no such route
    existed).

    Reads the exact file LocalStorageProvider.upload() wrote — same
    STORAGE_LOCAL_PATH env var (default ".agent-data"), same
    "job-{id}.json" naming — and returns it verbatim, matching what
    LocalStorageProvider.download() expects to parse on the reading side.
    """
    from pathlib import Path

    from starlette.responses import JSONResponse, Response

    job_id = request.path_params["job_id"]
    base_dir = os.environ.get("STORAGE_LOCAL_PATH") or ".agent-data"
    base_path = Path(base_dir)
    path = base_path / f"job-{job_id}.json"
    if not path.is_file():
        # TEMPORARY real diagnostic (2026-08-19): job #56619's submit()
        # succeeded on-chain (real tx_hash logged) but this same route,
        # same process, no restart, 404'd right after. Rather than guess
        # at a second fix, report the ACTUAL resolved paths + directory
        # contents so the real mismatch is visible, not assumed. Remove
        # once the real cause is found and fixed for good.
        try:
            listing = sorted(p.name for p in base_path.iterdir()) if base_path.is_dir() else None
        except Exception as e:  # noqa: BLE001 — diagnostic only
            listing = f"<error listing: {e}>"
        return JSONResponse({
            "error": f"no deliverable on disk for job {job_id}",
            "debug_base_dir_raw": base_dir,
            "debug_base_dir_resolved": str(base_path.resolve()),
            "debug_expected_path": str(path.resolve()),
            "debug_base_dir_exists": base_path.is_dir(),
            "debug_dir_listing": listing,
            "debug_cwd": str(Path.cwd()),
        }, status_code=404)
    return Response(path.read_text(encoding="utf-8"), media_type="application/json")


def _ping_status():
    """GET /ping status fed to AgentCore: HEALTHY_BUSY while a background delivery
    is in flight, else HEALTHY.

    notify_funded acks immediately and runs the slow work (LLM + on-chain submit)
    in the background. Reporting HEALTHY_BUSY tells AgentCore the runtime is still
    working, so the scale-to-zero runtime is NOT reaped on idle before delivery
    lands (bounded by the session max-lifetime; ≤8h)."""
    from bedrock_agentcore.runtime.models import PingStatus

    return PingStatus.HEALTHY_BUSY if executor.is_busy() else PingStatus.HEALTHY


# --- JSON-RPC error hardening -------------------------------------------------
# a2a-sdk builds -32602 (InvalidParams) / -32600 (InvalidRequest) JSON-RPC error
# responses from a Pydantic ValidationError, and Pydantic embeds an ``input`` key
# in each error entry that echoes the caller's raw request body back to them
# (a2a/server/apps/jsonrpc/jsonrpc_app.py). It only ever reflects the CALLER'S OWN
# input to that same caller (not cross-tenant), so this is low-severity, but we
# strip ``input`` from outgoing JSON-RPC error data anyway — no reason to echo
# request bodies. This is a tiny pure-ASGI wrapper (no SDK edit) that rewrites the
# response body only for JSON-RPC error payloads; every other response passes
# through untouched.
def _strip_error_input(app):
    async def _wrapped(scope, receive, send):
        if scope["type"] != "http":
            await app(scope, receive, send)
            return

        # `buffer` is decided from the response start (content-type): we only
        # buffer+rewrite JSON bodies (the JSON-RPC error path). SSE / any other
        # response streams through unbuffered so streaming is never broken.
        state: dict = {"buffer": False, "start": None}
        chunks: list[bytes] = []

        async def _capture(message):
            if message["type"] == "http.response.start":
                ctype = dict(message.get("headers", [])).get(b"content-type", b"")
                state["buffer"] = b"application/json" in ctype.lower()
                state["start"] = message
                if not state["buffer"]:
                    await send(message)
            elif message["type"] == "http.response.body":
                if not state["buffer"]:
                    await send(message)
                    return
                chunks.append(message.get("body", b"") or b"")
                if message.get("more_body"):
                    return
                await _emit(send, state["start"], b"".join(chunks))
            else:
                await send(message)

        await app(scope, receive, _capture)

    return _wrapped


async def _emit(send, start_message, body: bytes):
    new_body = body
    try:
        payload = json.loads(body)
        # JSON-RPC error: {"jsonrpc": "2.0", "error": {"data": [ {...,"input":..}]}}
        data = payload.get("error", {}).get("data")
        if isinstance(data, list) and any(
            isinstance(e, dict) and "input" in e for e in data
        ):
            for e in data:
                if isinstance(e, dict):
                    e.pop("input", None)
            new_body = json.dumps(payload).encode("utf-8")
    except Exception:  # noqa: BLE001 — never let hardening break a response
        new_body = body

    if start_message is not None:
        headers = [
            (k, v)
            for (k, v) in start_message.get("headers", [])
            if k.lower() != b"content-length"
        ]
        headers.append((b"content-length", str(len(new_body)).encode("latin-1")))
        start_message = {**start_message, "headers": headers}
        await send(start_message)
    await send({"type": "http.response.body", "body": new_body, "more_body": False})


async def _warm_up_llm() -> None:
    """One real, throwaway LLM call at boot, BEFORE uvicorn starts accepting
    connections — so a real, measured cold-start cost never lands on a real
    request or on Render's health check.

    Real bug found + fixed 2026-08-19 (second half — see managed_model.py's
    _pre_warm_credit_cache for the first): even after fixing the Pieverse
    credit-check's blocking call, notify_funded deliveries kept getting
    killed by Render's "HTTP health check failed (timed out after 5
    seconds)". Proved it directly, locally, with a concurrent heartbeat
    coroutine racing the real generate_content_async call: the FIRST real
    completion call blocks the event loop for ~1.7-3.8s (something inside
    litellm/ADK doing synchronous cold-start work — likely a pricing/model
    table or tokenizer load — with no yield point). A SECOND call in the
    same process had ZERO stall and ran ~6x faster (2.19s vs 13.89s),
    confirming it's a one-time, cacheable cost, not a per-call cost.

    Fix: pay that cost once, right here, on the SAME event loop uvicorn is
    about to serve requests on (no separate thread/loop — this is a
    Starlette ``startup`` lifespan event, and uvicorn does not begin
    accepting connections, including Render's health check, until the
    lifespan startup phase completes). By the time any real job arrives,
    litellm's internal caches are already warm.

    Best-effort: any failure here is logged, not raised — worst case is
    reverting to the pre-fix cold-start cost on the first real request,
    never worse than before this existed.
    """
    log = logging.getLogger("seller-agent.main")
    try:
        t0 = time.monotonic()
        await _run_llm("Say hello in one short sentence.", session_id="startup-warmup")
        log.info("LLM warm-up completed in %.2fs", time.monotonic() - t0)
    except Exception:
        log.exception("LLM warm-up failed (non-fatal, continuing startup)")


if __name__ == "__main__":
    import uvicorn
    from bedrock_agentcore.runtime import build_a2a_app

    # build_a2a_app is serve_a2a's own builder (it returns the Starlette app
    # instead of running uvicorn), so the /ping + card + JSON-RPC wiring is
    # identical to serve_a2a — we only interpose the error-input stripper before
    # serving.
    app = build_a2a_app(executor, agent_card, ping_handler=_ping_status)
    # Real, tested against this exact installed Starlette version (1.6.0):
    # it has no add_event_handler / router.on_startup (both raised
    # AttributeError when tried locally, caught before ever deploying).
    # The real, current API is router.lifespan_context — a callable that
    # takes `app` and returns an async context manager. build_a2a_app()
    # leaves it as Starlette's own no-op _DefaultLifespan (confirmed by
    # inspection), so replacing it outright is safe — there is nothing of
    # build_a2a_app's own to preserve here.
    from contextlib import asynccontextmanager

    @asynccontextmanager
    async def _lifespan(_app):
        await _warm_up_llm()
        yield

    app.router.lifespan_context = _lifespan
    # Real fix (see _serve_deliverable's own docstring): serve the
    # deliverable submit() publishes on-chain as {ERC8183_AGENT_URL}
    # /job/{id}/response — nothing did before this. ERC8183_AGENT_URL
    # itself is a Render env var (set to
    # https://explainer-agent.onrender.com/erc8183), not hardcoded here.
    app.add_route("/erc8183/job/{job_id}/response", _serve_deliverable, methods=["GET"])
    # Registered on the INNER Starlette app, not the _strip_error_input
    # wrapper below: _wrapped() only intercepts scope["type"] == "http" and
    # forwards everything else (including "lifespan") straight to `app`, so
    # this still fires correctly.
    app = _strip_error_input(app)

    uvicorn.run(
        app,
        # AgentCore's A2A contract is 0.0.0.0:9000. Do not honor the HTTP
        # protocol's $PORT=8080 convention here; AGENT_PORT is the local-dev /
        # rendered-container override.
        host=os.environ.get("AGENT_BIND_HOST") or "0.0.0.0",
        port=int(os.environ.get("AGENT_PORT") or "9000"),
        log_level="info",
    )
