[profile.default]
src = "src"
test = "test"
script = "script"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
solc_version = "0.8.24"
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
]
